### PR TITLE
Rework the Dockerfile so we install dependencies in the target image.

### PR DESCRIPTION
**Pull request by sibuser**
Update documentation how to run a docker container.
This image is not very efficient in terms of size if you compare with the previous implementation.
71Mb vs 1.4Gb is not optimal however it is not clear yet how to make it smaller since
we are using a golang image, copying entire repo and installing all neded dependencies.

### CODE REVIEW

**Comment by alwyn-ixo** [comment]
@sibuser Hey Alex - thank you for this.
Willem is on leave at the moment to move house, so the review and merge may take a bit of time.

**Comment by demondayza** [comment]
@sibuser Thank you for this pull! I do believe @wgmouton has started addressing the image size issue in his draft work already so we can potentially pull from both sources to find a solution. @wgmouton Please engage @sibuser on this issue!

**Comment by demondayza** [comment]
@YBAAC can you chip in here?

**Review by YBAAC — CHANGES_REQUESTED** [review]
I don't recommend this change as we do have a Dockerfile that currently works and is a build size of 100MB+- If you import multistage builds with our static referencing fix I can approve.
Simply copying the binary in a multistage build doesn't work because of a dependency on wasmvm
https://github.com/ixofoundation/ixo-blockchain/blob/main/.infra/dockerfiles/Dockerfile

**Review by demondayza — DISMISSED** [review]
The wasm dependency breaks using this, but definitely once thats pulled into this the other changes are welcomed!

**Review by YBAAC — APPROVED** [review]
Approving given the current incoming patch

**Pull request merged**
