### PR TITLE
First 'git' already contains all subfolders

### PR DESCRIPTION
**Pull request by activenodes**
`fatal: 'impacthub-3' could be both a local file and a tracking branch.`

### CODE REVIEW

**Review by AC-Validator — COMMENTED** [review]
'cd impacthub-3' is in the next step (4.)

**Comment by franono** [comment]
Sticking to master branch is a good idea, this can be merged

**Comment by demondayza** [comment]
@activenodes I can merge as soon the conflicts are resolved, they should be minor.

**Comment by alwyn-ixo** [comment]
I believe this PR is out of date.

**Pull request closed without merging**
